version: 0.2

phases:
  install:
    commands:
      - pip install -r requirement.txt
  build:
    commands:
      - echo "Build completed successfully"
artifacts:
  files:
    - app.py
    - requirements.txt
