version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install flask
  build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'

